name = "PadicCoding"
uuid = "689415c1-14d6-4206-93dc-cd924a8800ca"
version = "0.1.0"
authors = ["Anatoly Rodionov <ayarodionov@gmail.com>"]

[compat]
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
